version: '3.8'

services:
  vllama:
    build: .
    image: vllama:latest
    container_name: vllama
    runtime: nvidia
    environment:
      # Model configuration
      - MODEL_NAME=Qwen/Qwen2.5-7B-Instruct
      - GPU_MEMORY_UTILIZATION=0.9
      - MAX_NUM_SEQS=256

      # Server configuration
      - VLLAMA_HOST=0.0.0.0
      - VLLAMA_PORT=11434
      - VLLM_PORT=8100

      # Logging
      - RUST_LOG=info
      - VLLAMA_LOG_FORMAT=json

      # NVIDIA GPU support
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

    ports:
      - "11434:11434"  # vllama API
      - "8100:8100"    # vLLM OpenAI API (optional, for debugging)

    volumes:
      # Cache HuggingFace models on host
      - huggingface-cache:/root/.cache/huggingface
      # Persist logs
      - ./logs:/var/log/vllama

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

    command: >
      vllama serve
      --host 0.0.0.0
      --port 11434
      --model ${MODEL_NAME}
      --gpu-memory-utilization ${GPU_MEMORY_UTILIZATION}
      --max-num-seqs ${MAX_NUM_SEQS}

  # Optional: Prometheus for metrics
  prometheus:
    image: prom/prometheus:latest
    container_name: vllama-prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    restart: unless-stopped
    profiles:
      - monitoring

  # Optional: Grafana for dashboards
  grafana:
    image: grafana/grafana:latest
    container_name: vllama-grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - prometheus
    profiles:
      - monitoring

volumes:
  huggingface-cache:
  prometheus-data:
  grafana-data:
