[project]
name = "vllama-services"
version = "0.1.0"
description = "Python inference services for vLLama"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.115.0",
    "uvicorn[standard]>=0.30.0",
    "pydantic>=2.0.0",
]

[project.optional-dependencies]
vllm = [
    "vllm>=0.5.0",
]
